mod day01;
mod day02;
mod day03;
mod day04;
mod day06;
mod day07;
mod input_helper;
pub use day01::main as one;
pub use day02::main as two;
pub use day03::main as three;
pub use day04::main as four;
pub use day06::main as six;
pub use day07::main as seven;
